version: '3.8'
services:
  backend:
    build: .
    container_name: haunted-empire-backend
    ports:
      - "3002:3002"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    command: node index.js
